from pydantic import BaseModel
from typing import Protocol
from sqlalchemy.orm import Session
from typing import List

from backend.src.domain.entities.recipe import Recipe

class RecipeRepository(Protocol):
    async def get(self, db: Session, id: int) -> Recipe: ...
    async def create(self, db: Session, recipe: Recipe) -> Recipe: ...
    async def update(self, db: Session, recipe: Recipe) -> Recipe: ...
    async def get_all(self, db: Session, user_id: int) -> List[Recipe]: ...
