from pydantic import BaseModel
from typing import Protocol
from sqlalchemy.orm import Session

from backend.src.domain.entities.user import User

class UserRepository(Protocol):
    async def get(self, db: Session, id: int) -> User: ...
    async def get_by_name(self, db: Session, name: str) -> User: ...
    async def get_by_email(self, db: Session, email: str) -> User: ...
    def create(self, db: Session, username: str, email: str, hash: str) -> User: ...
