from pydantic import BaseModel
from typing import Protocol
from sqlalchemy.orm import Session

#from backend.src.interface.database.database import User

class UserRepository(Protocol):
    async def get(self, db: Session, id: int): ...
    async def get_by_name(self, db: Session, name: str): ...
    async def get_by_name(self, db: Session, email: str): ...
    def create(self, db: Session, username: str, email: str, hash: str): ...
